var fakedata = {
	dataset: {
		dataset_id: 'rdu-weather-history',
		dataset_uid: 'da_i2m3v1',
		has_records: true,
		data_visible: true,
		label1: 'Date',
		typeq: 'date',
		namea: 'date',

		description1111111111112222222222ddddd: {
			ru: 'Low Temperature of the day in Fahrenheit',
			fr: 'Low Temperature of the day in Fahrenheit',
			en: 'Low Temperature of the day in Fahrenheit',
			nl: 'Low Temperature of the day in Fahrenheit',
			pt: 'Low Temperature of the day in Fahrenheit',
			no: 'Low Temperature of the day in Fahrenheit',
			ca: 'Low Temperature of the day in Fahrenheit',
			de: 'Low Temperature of the day in Fahrenheit',
			sv: 'Low Temperature of the day in Fahrenheit',
			it: 'Low Temperature of the day in Fahrenheit',
			fa: 'Low Temperature of the day in Fahrenheit',
			ar: 'Low Temperature of the day in Fahrenheit',
			eu: 'Low Temperature of the day in Fahrenheit',
			fi: 'Low Temperature of the day in Fahrenheit',
			es: 'Low Temperature of the day in Fahrenheit',
		},
		label2: 'TemperatureMin',
		typeqw: 'double',
		nameaa: 'temperaturemin',
		annotations121: {},
	},

	description1: {
		ru: 'High Temperature of the day in Fahrenheit ',
		fr: 'High Temperature of the day in Fahrenheit ',
		en: 'High Temperature of the day in Fahrenheit ',
		nl: 'High Temperature of the day in Fahrenheit ',
		pt: 'High Temperature of the day in Fahrenheit ',
		no: 'High Temperature of the day in Fahrenheit ',
		ca: 'High Temperature of the day in Fahrenheit ',
		de: 'High Temperature of the day in Fahrenheit ',
		sv: 'High Temperature of the day in Fahrenheit ',
		it: 'High Temperature of the day in Fahrenheit ',
		fa: 'High Temperature of the day in Fahrenheit ',
		ar: 'High Temperature of the day in Fahrenheit ',
		eu: 'High Temperature of the day in Fahrenheit ',
		fi: 'High Temperature of the day in Fahrenheit ',
		es: 'High Temperature of the day in Fahrenheit ',
	},
	label3: 'TemperatureMax',
	typeqwe: 'double',
	nameaaa: 'temperaturemax',
	annotations121121: {},

	description11: {
		ru: 'The amount of precipitation in inches',
		fr: 'The amount of precipitation in inches',
		en: 'The amount of precipitation in inches',
		nl: 'The amount of precipitation in inches',
		pt: 'The amount of precipitation in inches',
		no: 'The amount of precipitation in inches',
		ca: 'The amount of precipitation in inches',
		de: 'The amount of precipitation in inches',
		sv: 'The amount of precipitation in inches',
		it: 'The amount of precipitation in inches',
		fa: 'The amount of precipitation in inches',
		ar: 'The amount of precipitation in inches',
		eu: 'The amount of precipitation in inches',
		fi: 'The amount of precipitation in inches',
		es: 'The amount of precipitation in inches',
	},
	label32: 'Precipitation',
	typeqwer: 'double',
	nameaaaa: 'precipitation',
	annotations121121212: {},

	description111: {
		ru: 'The amount of snowfall in inches',
		fr: 'The amount of snowfall in inches',
		en: 'The amount of snowfall in inches',
		nl: 'The amount of snowfall in inches',
		pt: 'The amount of snowfall in inches',
		no: 'The amount of snowfall in inches',
		ca: 'The amount of snowfall in inches',
		de: 'The amount of snowfall in inches',
		sv: 'The amount of snowfall in inches',
		it: 'The amount of snowfall in inches',
		fa: 'The amount of snowfall in inches',
		ar: 'The amount of snowfall in inches',
		eu: 'The amount of snowfall in inches',
		fi: 'The amount of snowfall in inches',
		es: 'The amount of snowfall in inches',
	},
	label4: 'Snowfall',
	typeqwert: 'double',
	nameaaaaa: 'snowfall',
	annotations12112121212: {},

	description1111: {
		ru: 'Depth of Snow in inches',
		fr: 'Depth of Snow in inches',
		en: 'Depth of Snow in inches',
		nl: 'Depth of Snow in inches',
		pt: 'Depth of Snow in inches',
		no: 'Depth of Snow in inches',
		ca: 'Depth of Snow in inches',
		de: 'Depth of Snow in inches',
		sv: 'Depth of Snow in inches',
		it: 'Depth of Snow in inches',
		fa: 'Depth of Snow in inches',
		ar: 'Depth of Snow in inches',
		eu: 'Depth of Snow in inches',
		fi: 'Depth of Snow in inches',
		es: 'Depth of Snow in inches',
	},
	label45: 'SnowDepth',
	typeqwerta: 'double',
	nameaaaaaa: 'snowdepth',
	annotations121121212122: {},

	description11111: {
		ru: 'Average Wind Speed (Miles Per Hour)',
		fr: 'Average Wind Speed (Miles Per Hour)',
		en: 'Average Wind Speed (Miles Per Hour)',
		nl: 'Average Wind Speed (Miles Per Hour)',
		pt: 'Average Wind Speed (Miles Per Hour)',
		no: 'Average Wind Speed (Miles Per Hour)',
		ca: 'Average Wind Speed (Miles Per Hour)',
		de: 'Average Wind Speed (Miles Per Hour)',
		sv: 'Average Wind Speed (Miles Per Hour)',
		it: 'Average Wind Speed (Miles Per Hour)',
		fa: 'Average Wind Speed (Miles Per Hour)',
		ar: 'Average Wind Speed (Miles Per Hour)',
		eu: 'Average Wind Speed (Miles Per Hour)',
		fi: 'Average Wind Speed (Miles Per Hour)',
		es: 'Average Wind Speed (Miles Per Hour)',
	},
	label456: 'AvgWindSpeed',
	typeqwertas: 'double',
	nameaaaaaaa: 'avgwindspeed',
	annotations1211212121221: {},

	description111111: {
		ru: 'Direction of fastest 2-minute wind (degrees)',
		fr: 'Direction of fastest 2-minute wind (degrees)',
		en: 'Direction of fastest 2-minute wind (degrees)',
		nl: 'Direction of fastest 2-minute wind (degrees)',
		pt: 'Direction of fastest 2-minute wind (degrees)',
		no: 'Direction of fastest 2-minute wind (degrees)',
		ca: 'Direction of fastest 2-minute wind (degrees)',
		de: 'Direction of fastest 2-minute wind (degrees)',
		sv: 'Direction of fastest 2-minute wind (degrees)',
		it: 'Direction of fastest 2-minute wind (degrees)',
		fa: 'Direction of fastest 2-minute wind (degrees)',
		ar: 'Direction of fastest 2-minute wind (degrees)',
		eu: 'Direction of fastest 2-minute wind (degrees)',
		fi: 'Direction of fastest 2-minute wind (degrees)',
		es: 'Direction of fastest 2-minute wind (degrees)',
	},
	label4566: 'Fastest2MinWindDir',
	typeqwertasd: 'int',
	nameaaaaaaaa: 'fastest2minwinddir',
	annotations121121212122121: {},

	description1111111asas: {
		ru: 'Fastest 2-minute wind speed (MPH)',
		fr: 'Fastest 2-minute wind speed (MPH)',
		en: 'Fastest 2-minute wind speed (MPH)',
		nl: 'Fastest 2-minute wind speed (MPH)',
		pt: 'Fastest 2-minute wind speed (MPH)',
		no: 'Fastest 2-minute wind speed (MPH)',
		ca: 'Fastest 2-minute wind speed (MPH)',
		de: 'Fastest 2-minute wind speed (MPH)',
		sv: 'Fastest 2-minute wind speed (MPH)',
		it: 'Fastest 2-minute wind speed (MPH)',
		fa: 'Fastest 2-minute wind speed (MPH)',
		ar: 'Fastest 2-minute wind speed (MPH)',
		eu: 'Fastest 2-minute wind speed (MPH)',
		fi: 'Fastest 2-minute wind speed (MPH)',
		es: 'Fastest 2-minute wind speed (MPH)',
	},
	label09: 'Fastest2MinWindSpeed',
	typeqwertasdf: 'double',
	nameaaaaaaaaa: 'fastest2minwindspeed',
	annotations121121212122121221: {},

	description1111111asassasssaasas: {
		ru: 'Direction of fastest 5 second wind (degrees)',
		fr: 'Direction of fastest 5 second wind (degrees)',
		en: 'Direction of fastest 5 second wind (degrees)',
		nl: 'Direction of fastest 5 second wind (degrees)',
		pt: 'Direction of fastest 5 second wind (degrees)',
		no: 'Direction of fastest 5 second wind (degrees)',
		ca: 'Direction of fastest 5 second wind (degrees)',
		de: 'Direction of fastest 5 second wind (degrees)',
		sv: 'Direction of fastest 5 second wind (degrees)',
		it: 'Direction of fastest 5 second wind (degrees)',
		fa: 'Direction of fastest 5 second wind (degrees)',
		ar: 'Direction of fastest 5 second wind (degrees)',
		eu: 'Direction of fastest 5 second wind (degrees)',
		fi: 'Direction of fastest 5 second wind (degrees)',
		es: 'Direction of fastest 5 second wind (degrees)',
	},
	label099: 'Fastest5SecWindDir',
	typeqwertasdfg: 'int',
	nameaaaaaaaaaa: 'fastest5secwinddir',
	annotations1211212121221212211: {},

	description11111111: {
		ru: 'Fastest 5-second wind speed (MPH)',
		fr: 'Fastest 5-second wind speed (MPH)',
		en: 'Fastest 5-second wind speed (MPH)',
		nl: 'Fastest 5-second wind speed (MPH)',
		pt: 'Fastest 5-second wind speed (MPH)',
		no: 'Fastest 5-second wind speed (MPH)',
		ca: 'Fastest 5-second wind speed (MPH)',
		de: 'Fastest 5-second wind speed (MPH)',
		sv: 'Fastest 5-second wind speed (MPH)',
		it: 'Fastest 5-second wind speed (MPH)',
		fa: 'Fastest 5-second wind speed (MPH)',
		ar: 'Fastest 5-second wind speed (MPH)',
		eu: 'Fastest 5-second wind speed (MPH)',
		fi: 'Fastest 5-second wind speed (MPH)',
		es: 'Fastest 5-second wind speed (MPH)',
	},
	label0098: 'Fastest5SecWindSpeed',
	typeqwertasdfgh: 'double',
	nameaaaaaaaaaaa: 'fastest5secwindspeed',
	annotations12112121212212122111: {},

	description111111111: {
		ru: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		fr: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		en: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		nl: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		pt: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		no: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		ca: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		de: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		sv: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		it: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		fa: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		ar: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		eu: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		fi: 'Fog, ice fog, or freezing fog (may include heavy fog)',
		es: 'Fog, ice fog, or freezing fog (may include heavy fog)',
	},
	label000877: 'Fog',
	typeqwertasdfghx: 'text',
	nameaaaaaaaaaaaaalllllll: 'fog',
	annotations121121212122121221111: {},

	abc: {
		ru: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		fr: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		en: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		nl: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		pt: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		no: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		ca: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		de: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		sv: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		it: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		fa: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		ar: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		eu: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		fi: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
		es: 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
	},
	label00087867: 'FogHeavy',
	typeqwertasdfghxs: 'text',
	nameaaaaaaaaaaaaalll: 'fogheavy',
	annotations1211212121221212211111: {},

	description11111111111: {
		ru: 'Mist?',
		fr: 'Mist?',
		en: 'Mist?',
		nl: 'Mist?',
		pt: 'Mist?',
		no: 'Mist?',
		ca: 'Mist?',
		de: 'Mist?',
		sv: 'Mist?',
		it: 'Mist?',
		fa: 'Mist?',
		ar: 'Mist?',
		eu: 'Mist?',
		fi: 'Mist?',
		es: 'Mist?',
	},
	label00087897675: 'Mist',
	typeqwertasdfghxsd: 'text',
	nameaaaaaaaaaaaaaa: 'mist',
	annotations12112121212212122111111: {},

	description1111111111112: {
		ru: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		fr: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		en: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		nl: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		pt: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		no: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		ca: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		de: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		sv: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		it: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		fa: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		ar: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		eu: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		fi: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
		es: 'Rain (may include freezing rain, drizzle, and freezing drizzle)',
	},
	label1232: 'Rain',
	typeqwertasdfghxsdf: 'text',
	nameaaaaaaaaaaaaaaa: 'rain',
	annotations121121212122121221111111: {},

	descriptiodescription11111111111122aaaan1111111asassasssaasas: {
		ru: 'Ground Fog',
		fr: 'Ground Fog',
		en: 'Ground Fog',
		nl: 'Ground Fog',
		pt: 'Ground Fog',
		no: 'Ground Fog',
		ca: 'Ground Fog',
		de: 'Ground Fog',
		sv: 'Ground Fog',
		it: 'Ground Fog',
		fa: 'Ground Fog',
		ar: 'Ground Fog',
		eu: 'Ground Fog',
		fi: 'Ground Fog',
		es: 'Ground Fog',
	},
	label124: 'FogGround',
	typeqwertasdfghxsdfg: 'text',
	nameaaaaaaaaaaaaaaaaa: 'fogground',
	annotations1211212121221212211111111: {},

	descriptiodescription11111111111122aaaaaaaaan1111111asassasssaasas: {
		ru: 'Ice pellets, sleet, snow pellets, or small hail',
		fr: 'Ice pellets, sleet, snow pellets, or small hail',
		en: 'Ice pellets, sleet, snow pellets, or small hail',
		nl: 'Ice pellets, sleet, snow pellets, or small hail',
		pt: 'Ice pellets, sleet, snow pellets, or small hail',
		no: 'Ice pellets, sleet, snow pellets, or small hail',
		ca: 'Ice pellets, sleet, snow pellets, or small hail',
		de: 'Ice pellets, sleet, snow pellets, or small hail',
		sv: 'Ice pellets, sleet, snow pellets, or small hail',
		it: 'Ice pellets, sleet, snow pellets, or small hail',
		fa: 'Ice pellets, sleet, snow pellets, or small hail',
		ar: 'Ice pellets, sleet, snow pellets, or small hail',
		eu: 'Ice pellets, sleet, snow pellets, or small hail',
		fi: 'Ice pellets, sleet, snow pellets, or small hail',
		es: 'Ice pellets, sleet, snow pellets, or small hail',
	},
	label154454: 'Ice',
	typeqwertasdfghxsdfgh: 'text',
	nameaaaaaaaaaaaaaaaaaa: 'ice',
	annotations12112121212212122111111111: {},

	description111111111111222: {
		ru: 'Glaze or rime',
		fr: 'Glaze or rime',
		en: 'Glaze or rime',
		nl: 'Glaze or rime',
		pt: 'Glaze or rime',
		no: 'Glaze or rime',
		ca: 'Glaze or rime',
		de: 'Glaze or rime',
		sv: 'Glaze or rime',
		it: 'Glaze or rime',
		fa: 'Glaze or rime',
		ar: 'Glaze or rime',
		eu: 'Glaze or rime',
		fi: 'Glaze or rime',
		es: 'Glaze or rime',
	},
	label1544556: 'Glaze',
	typeqwertasdfghxsdfghj: 'text',
	nameaaaaaaaaaaaaaaaaaaaf: 'glaze',
	annotations121121212122121221111111111: {},

	description1111111111112222: {
		ru: 'Drizzle',
		fr: 'Drizzle',
		en: 'Drizzle',
		nl: 'Drizzle',
		pt: 'Drizzle',
		no: 'Drizzle',
		ca: 'Drizzle',
		de: 'Drizzle',
		sv: 'Drizzle',
		it: 'Drizzle',
		fa: 'Drizzle',
		ar: 'Drizzle',
		eu: 'Drizzle',
		fi: 'Drizzle',
		es: 'Drizzle',
	},
	label1544556436: 'Drizzle',
	typeqwertasdfghxsdfghjk: 'text',
	nameaaaaaaaaaaaaaaaaaaaff: 'drizzle',
	annotations1211212121221212211111111111: {},

	description11111111111122222: {
		ru: 'Snow, snow pellets, snow grains, or ice crystals',
		fr: 'Snow, snow pellets, snow grains, or ice crystals',
		en: 'Snow, snow pellets, snow grains, or ice crystals',
		nl: 'Snow, snow pellets, snow grains, or ice crystals',
		pt: 'Snow, snow pellets, snow grains, or ice crystals',
		no: 'Snow, snow pellets, snow grains, or ice crystals',
		ca: 'Snow, snow pellets, snow grains, or ice crystals',
		de: 'Snow, snow pellets, snow grains, or ice crystals',
		sv: 'Snow, snow pellets, snow grains, or ice crystals',
		it: 'Snow, snow pellets, snow grains, or ice crystals',
		fa: 'Snow, snow pellets, snow grains, or ice crystals',
		ar: 'Snow, snow pellets, snow grains, or ice crystals',
		eu: 'Snow, snow pellets, snow grains, or ice crystals',
		fi: 'Snow, snow pellets, snow grains, or ice crystals',
		es: 'Snow, snow pellets, snow grains, or ice crystals',
	},
	label154455643654: 'Snow',
	typeqwertasdfghxsdfghjku: 'text',
	nameaaaaaaaaaaaaaaaaaaaa: 'snow',
	annotations12112121212212122111111111111: {},

	description111111111111222222: {
		ru: 'Freezing rain',
		fr: 'Freezing rain',
		en: 'Freezing rain',
		nl: 'Freezing rain',
		pt: 'Freezing rain',
		no: 'Freezing rain',
		ca: 'Freezing rain',
		de: 'Freezing rain',
		sv: 'Freezing rain',
		it: 'Freezing rain',
		fa: 'Freezing rain',
		ar: 'Freezing rain',
		eu: 'Freezing rain',
		fi: 'Freezing rain',
		es: 'Freezing rain',
	},
	label154455643655463: 'FreezingRain',
	typeqwertasdfghxsdfghjku6: 'text',
	nameaaaaaaaaaaaaaaaaaaaaa: 'freezingrain',
	annotations121121212122121221111111111111: {},

	description11111111111122222222: {
		ru: 'Smoke or haze',
		fr: 'Smoke or haze',
		en: 'Smoke or haze',
		nl: 'Smoke or haze',
		pt: 'Smoke or haze',
		no: 'Smoke or haze',
		ca: 'Smoke or haze',
		de: 'Smoke or haze',
		sv: 'Smoke or haze',
		it: 'Smoke or haze',
		fa: 'Smoke or haze',
		ar: 'Smoke or haze',
		eu: 'Smoke or haze',
		fi: 'Smoke or haze',
		es: 'Smoke or haze',
	},
	label154455643655463654: 'SmokeHaze',
	typeqwertasdfghxsdfghjku65: 'text',
	nameaaaaaaaaaaaaaaaaaaaaaaaa: 'smokehaze',
	annotations1211212121221212211111111111111: {},

	description111111111111222222222: {
		ru: 'Thunder',
		fr: 'Thunder',
		en: 'Thunder',
		nl: 'Thunder',
		pt: 'Thunder',
		no: 'Thunder',
		ca: 'Thunder',
		de: 'Thunder',
		sv: 'Thunder',
		it: 'Thunder',
		fa: 'Thunder',
		ar: 'Thunder',
		eu: 'Thunder',
		fi: 'Thunder',
		es: 'Thunder',
	},
	label154455643655463656354: 'Thunder',
	typeqwertasdfghxsdfghjku654: 'text',
	nameaaaaaaaaaaaaaaaaaaaaaaaaaa: 'thunder',
	annotations121121212122121221111111111111111: {},

	description1111111111112222222222: {
		ru: 'High or damaging winds',
		fr: 'High or damaging winds',
		en: 'High or damaging winds',
		nl: 'High or damaging winds',
		pt: 'High or damaging winds',
		no: 'High or damaging winds',
		ca: 'High or damaging winds',
		de: 'High or damaging winds',
		sv: 'High or damaging winds',
		it: 'High or damaging winds',
		fa: 'High or damaging winds',
		ar: 'High or damaging winds',
		eu: 'High or damaging winds',
		fi: 'High or damaging winds',
		es: 'High or damaging winds',
	},
	label15445564367: 'HighWind',
	typeqwertasdfghxsdfghjku6543: 'text',
	nameaaaaaaaaaaaaaaaaaaaaaaaaaaa: 'highwind',
	annotations1211212121221212211111111111111111: {},

	description1111111111112222222222d: {
		ru: 'Hail (may include small hail)',
		fr: 'Hail (may include small hail)',
		en: 'Hail (may include small hail)',
		nl: 'Hail (may include small hail)',
		pt: 'Hail (may include small hail)',
		no: 'Hail (may include small hail)',
		ca: 'Hail (may include small hail)',
		de: 'Hail (may include small hail)',
		sv: 'Hail (may include small hail)',
		it: 'Hail (may include small hail)',
		fa: 'Hail (may include small hail)',
		ar: 'Hail (may include small hail)',
		eu: 'Hail (may include small hail)',
		fi: 'Hail (may include small hail)',
		es: 'Hail (may include small hail)',
	},
	label154455643677: 'Hail',
	typeqwertasdfghxsdfghjku65433: 'text',
	nameaaaaaaaaaaaaaaaaaaaaaaaaaaaa: 'hail',
	annotations12112121212212122111111111111111111: {},

	description1111111111112222222222dd: {
		ru: 'Blowing or drifting snow',
		fr: 'Blowing or drifting snow',
		en: 'Blowing or drifting snow',
		nl: 'Blowing or drifting snow',
		pt: 'Blowing or drifting snow',
		no: 'Blowing or drifting snow',
		ca: 'Blowing or drifting snow',
		de: 'Blowing or drifting snow',
		sv: 'Blowing or drifting snow',
		it: 'Blowing or drifting snow',
		fa: 'Blowing or drifting snow',
		ar: 'Blowing or drifting snow',
		eu: 'Blowing or drifting snow',
		fi: 'Blowing or drifting snow',
		es: 'Blowing or drifting snow',
	},
	label1544556436776: 'BlowingSnow',
	typeqwertasdfghxsdfghjku654333: 'text',
	nameaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: 'blowingsnow',
	annotations121121212122121221111111111111111111: {},

	description1111111111112222222222ddd: {
		ru:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		fr:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		en:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		nl:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		pt:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		no:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		ca:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		de:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		sv:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		it:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		fa:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		ar:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		eu:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		fi:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
		es:
			'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
	},
	label154455643677633: 'Dust',
	typeqwertasdfghxsdfghjku6543334: 'text',
	nameaaaaaaaaaaaaaaaaaaaaaaaaaaaaaass: 'dust',
	annotations1211212121221212211111111111111111111: {},

	description1111111111112222222222dddd: {
		ru: 'Ice fog or freezing fog',
		fr: 'Ice fog or freezing fog',
		en: 'Ice fog or freezing fog',
		nl: 'Ice fog or freezing fog',
		pt: 'Ice fog or freezing fog',
		no: 'Ice fog or freezing fog',
		ca: 'Ice fog or freezing fog',
		de: 'Ice fog or freezing fog',
		sv: 'Ice fog or freezing fog',
		it: 'Ice fog or freezing fog',
		fa: 'Ice fog or freezing fog',
		ar: 'Ice fog or freezing fog',
		eu: 'Ice fog or freezing fog',
		fi: 'Ice fog or freezing fog',
		es: 'Ice fog or freezing fog',
	},
	label154455643677633333: 'FreezingFog',
	typeqwertasdfghxsdfghjku65433345: 'text',
	nameaaaaaaaaaaaaaaaaaaaaaaaaaaaaaassssss: 'freezingfog',
	annotations12112121212212122111111111111111111111: {},
}

console.log(fakedata)
